name: fastaiv2
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch 
  - torchvision 
  - cpuonly
  - fastai
  - bqplot
  - ipympl
  - ipyvolume
  - scipy
  - voila
